### Initialize Tensor Objects

In [2]:
import torch

# intialize a tensor
x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])

In [4]:
# access tensor object's shape and data type

print(x.shape) # output: one entity of two items
print(y.shape) # output: two entities of one item each

print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [5]:
x = torch.tensor([False, 1, 2.0])
print(x)

tensor([0., 1., 2.])


In [6]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# 3 rows, 4 cols of values from 0-10
torch.randint(low=0, high=10, size=(3,4))

tensor([[2, 4, 8, 6],
        [0, 7, 0, 9],
        [8, 5, 5, 7]])

In [9]:
# generate random numbers between 0 and 1
torch.rand(3, 4)

tensor([[0.5739, 0.2111, 0.9440, 0.2486],
        [0.3701, 0.9533, 0.1963, 0.5902],
        [0.5840, 0.5834, 0.3089, 0.6483]])

In [10]:
# generate numbers that follow a normal distribution with 3 rows, 4 cols
torch.randn((3,4))

tensor([[ 1.8161,  0.3695,  0.9154,  1.8031],
        [ 0.6939, -0.0218, -1.3462,  1.5386],
        [ 0.9130, -1.6326, -1.0760, -0.4917]])

In [13]:
import numpy as np

# convert numpy arr into a Torch tensor
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
