### Build Neural Network with PyTorch

In [1]:
import torch
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]

In [2]:
# convert input lists to tensor objects
X = torch.tensor(x).float() # good practice to have tensor objects as floats or long ints, multiplied by decimal values anyway
Y = torch.tensor(y).float()

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
X = X.to(device)
Y = Y.to(device)

In [4]:
# define NN architecture

import torch.nn as nn

class MyNeuralNet(nn.Module): # nn.Module is the base class for all NN modules
    def __init__(self):
        super().__init__() # initialize all components of a nn.Module
        self.input_to_hidden_layer = nn.Linear(2,8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8,1)
    
    # define forward propagation layer in NN
    def forward(self, x): # mandatory to use 'forward' since PyTorch reserved this function as method for performing forward prop
        x = self.input_to_hidden_layer(x)
        x = self.hidden_layer_activation(x)
        x = self.hidden_to_output_layer(x)
        return x


In [5]:
# access initial weights of each of the components
mynet = MyNeuralNet().to(device) # register MyNeuralNet class object to device

In [6]:
# aside: access weight and bias of each layer
mynet.input_to_hidden_layer.weight

Parameter containing:
tensor([[-0.1639, -0.5277],
        [-0.0859,  0.6983],
        [ 0.5017,  0.0070],
        [-0.0299,  0.3474],
        [-0.6542,  0.5754],
        [ 0.1120,  0.5920],
        [ 0.2550,  0.1723],
        [-0.3843, -0.5489]], requires_grad=True)

In [7]:
# aside cont.
mynet.parameters()

for par in mynet.parameters():
    print(par)

Parameter containing:
tensor([[-0.1639, -0.5277],
        [-0.0859,  0.6983],
        [ 0.5017,  0.0070],
        [-0.0299,  0.3474],
        [-0.6542,  0.5754],
        [ 0.1120,  0.5920],
        [ 0.2550,  0.1723],
        [-0.3843, -0.5489]], requires_grad=True)
Parameter containing:
tensor([ 0.1207, -0.5223, -0.1440, -0.4131,  0.5316,  0.6701, -0.1688,  0.2678],
       requires_grad=True)
Parameter containing:
tensor([[ 0.1127,  0.0253, -0.0211, -0.3534,  0.1238,  0.3418,  0.1418, -0.1656]],
       requires_grad=True)
Parameter containing:
tensor([0.3271], requires_grad=True)


In [ ]:
# aside cont. alt way to define model with nn.Parameter

class MyNeuralNet(nn.Module): # nn.Module is the base class for all NN modules
    def __init__(self):
        super().__init__() # initialize all components of a nn.Module
        self.input_to_hidden_layer = nn.Parameter(torch.rand(2,8))
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Parametere(torch.rand(8,1))
    
    # define forward propagation layer in NN
    def forward(self, x): # mandatory to use 'forward' since PyTorch reserved this function as method for performing forward prop
        x = x @ self.input_to_hidden_layer
        x = self.hidden_layer_activation(x)
        x = x @ self.input_to_output_layer
        return x

loss_func = nn.MSELoss() # define the loss function that we optimize for
_Y = mynet(X) # gets output values when input is passed
loss_value = loss_func(_Y, Y) # when computing loss, always send prediction (_<variable) first, then ground truth (PyTorch convention)
print(loss_value)

tensor(70.3213, grad_fn=<MseLossBackward0>)
