### Tensor Operations

In [ ]:
import torch
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(x*10)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


In [27]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = x.add(10)
print(y)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])


In [ ]:
# reshape tensor with squeeze method
# provide axis index to remove, only applicable when dimension size is exactly 1
x = torch.randn(10, 1, 10)
z1 = torch.squeeze(x, 1) # similar to np.squeeze()
# same operation can be directly performed on x 
# by calling squeeze and the dimension to squeeze out
z2 = x.squeeze(1)
assert torch.all(z1 == z2)
# all the elements in both tensors are equal
print('Squeeze:\n', x.shape, z1.shape)

Squeeze:
 torch.Size([10, 1, 10]) torch.Size([10, 10])


In [ ]:
# unsqueeze to add dimension to the matrix
x = torch.randn(10, 10)
print("x.shape", x.shape)
z1 = x.unsqueeze(0) # inserts new axis at i=0
print("z1.shape", z1.shape)

# same can be achieved using [None] indexing
# adding None will auto create a fake dim at the specified axis
x = torch.randn(10,10)
z2, z3, z4 = x[None], x[:,None], x[:,:,None] # each colon represent one dimension
print(z2.shape, z3.shape, z4.shape)


x.shape torch.Size([10, 10])
z1.shape torch.Size([1, 10, 10])
torch.Size([1, 10, 10]) torch.Size([10, 1, 10]) torch.Size([10, 10, 1])


In [ ]:
# matrix multiplication of two different tensors
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(torch.matmul(x, y))
print(x@y)

In [ ]:
# concatenante tensors
import torch
x = torch.randn(10,10,10)
z = torch.cat([x,x], axis=0) # np.concatenate()
print('Cat axis 0:', x.shape, z.shape)

z = torch.cat([x,x], axis=1) # concatenates on 1st dimension
print('Cat axis 1:', x.shape, z.shape)

Cat axis 0: torch.Size([10, 10, 10]) torch.Size([20, 10, 10])
Cat axis 1: torch.Size([10, 10, 10]) torch.Size([10, 20, 10])


In [ ]:
# extract maximum value in a tensor
x = torch.arange(25).reshape(5,5)
print('Max:', x.shape, x.max())

Max: torch.Size([5, 5]) tensor(24)


In [41]:
print(x)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


In [39]:
# extract maximum value along with the row index
x.max(dim=0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

In [40]:
# get max across columns
m, argm = x.max(dim=1)
print('Max in axis 1:\n', m, argm)

Max in axis 1:
 tensor([ 4,  9, 14, 19, 24]) tensor([4, 4, 4, 4, 4])


In [42]:
# permute the dimensions of a tensor object
x = torch.randn(10, 20, 30)
z = x.permute(2,0,1) # np.permute()
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([10, 20, 30]) torch.Size([30, 10, 20])
